points_per_epoch=400
frames_per_point=15
dense_activation='elu'
conv_layers=4
conv_features=5
conv_features_depth_mul=1.5
kernel_size=(3,7,7)
conv_separable=False
conv_activation='elu'
stride_t=1
stride_xy=1
crop_w = 300
crop_h = 300
max_pool_first=True
max_pool_size_t=1
max_pool_size_xy=3
max_pool_first_size_t=1
max_pool_first_size_xy=2
first_dense_layer=200
dense_layers=5
optimizer='adam'
n_epochs=100
individuals_min_dist=50
